parameters:
- name: BxlCommonArgs # We reuse these across jobs like a constant
  type: string

- name: pool
  type: object

- name: sdkVersion
  type: string

- name: preBuildSteps
  type: stepList
  default: []

jobs:
- template: job-build-selfhost-base.yml
  parameters:
    validationName: ExternalRelease
    cacheUniverse: bxlselfhostpublic
    internal: false
    publishTestResults: true
    pool: ${{ parameters.pool }}
    sdkVersion: ${{ parameters.sdkVersion }}
    
    outputs:
    - output: pipelineArtifact
      targetPath: $(Build.SourcesDirectory)/Out/Logs/Bootstrap
      artifactName: BuildXL-Logs.External.Bootstrap.$(System.JobAttempt)
      condition: always()
      continueOnError: true
      displayName: Upload bootstrap Logs

    buildXLArguments: >-
      --use-dev 
      ${{ parameters.BxlCommonArgs }}
      /q:ReleaseLinux
      "/f:tag='test'"

    preBuildSteps:
    - ${{ each step in parameters.preBuildSteps }}:
      - ${{ step }}

      # 1. Bootstrap external bits manually - note this is a pre-build step for the actual "build" (which is running tests) 
      # We temporarily disable the EBPFSandbox when building with the LKG, until we produce official bits that can run EBPF
    - bash: >
        set -eu

        # Set a 60m timeout so we can catch hangs *and* get logs collected at the same time. Otherwise the whole job will timeout (check 'timeoutInMinutes' above).
        
        timeout --signal 9 60m bash bxl.sh 
        --use-adobuildrunner 
        --minimal
        --deploy-dev --release
        --runner-arg /cacheConfigLogGeneratedConfiguration:true 
        /logsDirectory:"Out/Logs/Bootstrap"
        /forceAddExecutionPermission-
        ${{ parameters.BxlCommonArgs }}
      displayName: Build
      env:
        AdoBuildRunnerInvocationKey: BuildExternal
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        workingDirectory: /home/subst
      # Clean up pinned BPF maps in case some of the map structure changed between the LKG and the current build.
    - task: Bash@3
      displayName: 'Cleanup pinned BPF maps'
      inputs:
        targetType: 'inline'
        script: |
          # We do this in case the LKG left some pinned maps that are incompatible with the current running daemon
          sudo find /sys/fs/bpf -mindepth 1 -maxdepth 1 -exec rm -rf {} \; || true
