parameters:
- name: BxlCommonArgs # We reuse these across jobs like a constant
  type: string

- name: pool
  type: object

- name: sdkVersion
  type: string

jobs:
- template: job-build-selfhost-base.yml
  parameters:
    validationName: PTrace
    cacheUniverse: bxlselfhostptrace
    internal: true
    publishTestResults: true
    pool: ${{ parameters.pool }}
    sdkVersion: ${{ parameters.sdkVersion }}
    
    # Enabling EBPF for validating ptrace doesn't make much sense
    # TODO: Move the logToKustoIngestUri to a common location once the feature becomes part of the LKG
    buildXLArguments: >-
      --minimal
      --use-dev 
      "/logToKustoIngestUri:https://buildxl.eastus2.kusto.windows.net/BuildXLProd?clientId=1fbd9009-2b6d-4363-9e4c-c4f677961c92&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&serviceConnectionId=861f8f3b-77a2-497a-a955-fbd921dc48de"
      ${{ parameters.BxlCommonArgs }}
      /forceEnableLinuxPTraceSandbox+
      /injectCacheMisses:0.3
      /enableLinuxEBPFSandbox-
    preBuildSteps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: current
        artifactName: Dev
        # Use the path that --deploy-dev would use, because we --use-dev in the validation
        targetPath: "$(Build.SourcesDirectory)/Out/Selfhost/Dev"
      displayName: Download BuildXL