parameters:
- name: BxlCommonArgs # We reuse these across jobs like a constant
  type: string

- name: internal
  type: boolean
  default: false

- name: outputArtifactName
  type: string
  default: 'ebpf-dev'

- name: sdkVersion
  type: string

jobs:
- template: job-build-selfhost-base.yml
  parameters:
    validationName: Bootstrap
    internal: ${{ parameters.internal }}

    pool:
    # The pool for the eBPF sandbox is Ubuntu 22.04 because it is currently the oldest platform we support.
    # The sandbox cannot be built on 20.04 due to lack of support for various eBPF features we use.
    # We also cannot build on a newer platform like Ubuntu 24.04 because we need to maintain backwards compatibility with older versions of glibc.
      name: BuildXL-DevOpsAgents-Selfhost-BuildCache
      image: ubuntu-22.04-PME-GPT
      os: linux
    sdkVersion: ${{ parameters.sdkVersion }}
    
    outputs:
    - output: pipelineArtifact
      targetPath: $(Build.SourcesDirectory)/Out/Bin
      artifactName: ${{ parameters.outputArtifactName }}
      condition: always()
      continueOnError: true
      displayName: Upload eBPF binaries for validations to consume

    buildXLArguments: --minimal "/f:output='*/linux-x64/bxl-ebpf-runner'" /q:ReleaseLinux /q:DebugLinux ${{ parameters.BxlCommonArgs }}