// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading;
using BuildXL.Pips;
using BuildXL.Pips.Graph;
using BuildXL.Pips.Operations;
using BuildXL.Utilities.Core;
using BuildXL.Utilities.Configuration;
using BuildXL.Utilities.Instrumentation.Common;

namespace BuildXL.Scheduler.Tracing
{
    /// <summary>
    /// Logging target for events triggered when a Pip fails.
    /// </summary>
    public sealed class DumpPipLiteExecutionLogTarget : ExecutionLogTargetBase
    {
        /// <summary>
        /// Used to hydrate pips from <see cref="PipId"/>s.
        /// </summary>
        private readonly PipTable m_pipTable;

        /// <summary>
        /// Execution context pointer for path table, symbol table, and string table.
        /// </summary>
        private readonly PipExecutionContext m_pipExecutionContext;

        /// <summary>
        /// Context for logging methods.
        /// </summary>
        private readonly LoggingContext m_loggingContext;

        /// <summary>
        /// Pip graph used to extract information from failing pip.
        /// </summary>
        private readonly PipGraph m_pipGraph;

        /// <summary>
        /// Path to the folder containing the failed pip logs - LogFolder/FailedPips.
        /// </summary>
        /// <remarks> This path is only created on the first Analyze call, if the analyzer is not called then it will not be created. </remarks>
        private readonly AbsolutePath m_logPath;

        /// <summary>
        /// Indicates whether the log path was already created.
        /// </summary>
        private bool m_logPathCreated;

        /// <summary>
        /// The maximum amount of log files that should be generated by this analyzer per run
        /// </summary>
        private readonly int m_maxLogFiles;

        /// <summary>
        /// The number of log files that have already been generated by this analyzer
        /// </summary>
        private int m_numLogFilesGenerated;

        /// <summary>
        /// If an error occured while logging, this will be set to true, and future logging requests will be skipped.
        /// </summary>
        private bool m_loggingErrorOccured;

        /// <summary>
        /// Whether further data collection should be skipped (error occurred or log limit reached).
        /// </summary>
        private bool ShouldSkipCollecting => m_loggingErrorOccured || m_numLogFilesGenerated >= m_maxLogFiles;

        /// <summary>
        /// Holds data collected by this execution log target until it is ready to be dumped.
        /// </summary>
        private readonly ConcurrentDictionary<PipId, ProcessExecutionMonitoringReportedEventData?> m_dynamicDataDictionary;

        /// <summary>
        /// Collects dependency violation data per pip, indexed by both violator and related pip IDs.
        /// Used both to trigger dumps and to include violation details in the JSON output.
        /// </summary>
        private readonly ConcurrentDictionary<PipId, List<DependencyViolationEventData>> m_dependencyViolations;

        /// <summary>
        /// Tracks pip IDs that have already been dumped to avoid duplicates.
        /// </summary>
        private readonly ConcurrentDictionary<PipId, byte> m_dumpedPips;

        /// <summary>
        /// Indicates whether any data other than just static pip data should be dumped.
        /// </summary>
        private readonly bool m_shouldDumpDynamicData;

        /// <summary>
        /// Intialize execution log target and create log directory.
        /// </summary>
        /// <remarks>
        /// If log directory creation fails, then runtime failed pip analysis will be disabled for this build.
        /// </remarks>
        public DumpPipLiteExecutionLogTarget(PipExecutionContext context, 
                                             PipTable pipTable, 
                                             LoggingContext loggingContext,
                                             IConfiguration configuration,
                                             PipGraph graph)
        {
            m_pipTable = pipTable;
            m_pipExecutionContext = context;
            m_loggingContext = loggingContext;
            m_pipGraph = graph;
            m_logPath = configuration.Logging.LogsDirectory.Combine(context.PathTable, "FailedPips"); // This path has not been created yet
            m_logPathCreated = false;
            m_loggingErrorOccured = false;
            m_maxLogFiles = configuration.Logging.DumpFailedPipsLogLimit.GetValueOrDefault();
            m_numLogFilesGenerated = 0;
            m_dynamicDataDictionary = new ConcurrentDictionary<PipId, ProcessExecutionMonitoringReportedEventData?>();
            m_dependencyViolations = new ConcurrentDictionary<PipId, List<DependencyViolationEventData>>();
            m_dumpedPips = new ConcurrentDictionary<PipId, byte>();
            m_shouldDumpDynamicData = configuration.Logging.DumpFailedPipsWithDynamicData.HasValue &&
                                      configuration.Logging.DumpFailedPipsWithDynamicData.Value &&
                                      ((configuration.Sandbox.UnsafeSandboxConfiguration.MonitorFileAccesses && 
                                      configuration.Sandbox.LogObservedFileAccesses) ||
                                      configuration.Sandbox.LogProcesses);

            if (!m_shouldDumpDynamicData &&
                configuration.Logging.DumpFailedPipsWithDynamicData.HasValue &&
                configuration.Logging.DumpFailedPipsWithDynamicData.Value)
            {
                Logger.Log.DumpPipLiteSettingsMismatch(m_loggingContext);
            }
        }

        /// <inheritdoc/>
        public override bool CanHandleWorkerEvents => true;

        /// <inheritdoc/>
        public override IExecutionLogTarget CreateWorkerTarget(uint workerId) => this;

        /// <summary>
        /// Hooks into the log target for pip execution performance data which will be called
        /// when a pip fails. This will then dump relevant information on the failing pip
        /// to a JSON file specified under <see cref="m_logPath"/>.
        /// The maximum number of logs generated can be specified using the 
        /// /DumpFailedPipsLogCount parameter.
        /// </summary>
        /// <remarks>
        /// If an error occurs while serializing/dumping the specified pip,
        /// then this analyzer will be disabled for the remainder of this build and
        /// a warning will be logged with more details.
        /// </remarks>
        public override void PipExecutionPerformance(PipExecutionPerformanceEventData data)
        {
            if (m_loggingErrorOccured)
            {
                return;
            }

            // Get the number of file access violations for this pip from ProcessPipExecutionPerformance if pip is a process pip
            var fileAccessViolationCount = 0;
            var processPerformance = data.ExecutionPerformance as ProcessPipExecutionPerformance;
            if (m_pipTable.GetPipType(data.PipId) == PipType.Process && processPerformance != null)
            {
                // Cancelled process pips have default perf with ProcessExecutionTime = Zero.
                // No need to dump them.
                if (processPerformance.ProcessExecutionTime == TimeSpan.Zero)
                {
                    return;
                }

                fileAccessViolationCount = processPerformance.FileMonitoringViolations.NumFileAccessViolationsNotAllowlisted;
            }

            bool pipActuallyFailed = data.ExecutionPerformance.ExecutionLevel == PipExecutionLevel.Failed;

            if (pipActuallyFailed || fileAccessViolationCount > 0 || m_dependencyViolations.ContainsKey(data.PipId))
            {
                DumpPip(data.PipId);
            }
            else
            {
                // The pip is not in a failed state, so it does not need to be dumped.
                // Clean up any collected dynamic data.
                if (m_shouldDumpDynamicData)
                {
                    m_dynamicDataDictionary.TryRemove(data.PipId, out _);
                }
            }
        }

        /// <summary>
        /// Records pips involved in dependency violations so they will be dumped.
        /// Both the violator and related pips are tracked.
        /// </summary>
        public override void DependencyViolationReported(DependencyViolationEventData data)
        {
            if (ShouldSkipCollecting)
            {
                return;
            }

            AddViolationForPip(data.ViolatorPipId, data);

            if (data.RelatedPipId.IsValid)
            {
                AddViolationForPip(data.RelatedPipId, data);
            }
        }

        /// <summary>
        /// Adds a dependency violation entry for the specified pip.
        /// Thread-safe: uses locking on the per-pip list.
        /// </summary>
        private void AddViolationForPip(PipId pipId, DependencyViolationEventData data)
        {
            m_dependencyViolations.AddOrUpdate(
                pipId,
                _ => new List<DependencyViolationEventData> { data },
                (_, existing) =>
                {
                    lock (existing)
                    {
                        existing.Add(data);
                    }

                    return existing;
                });
        }

        /// <summary>
        /// Flushes any remaining pips that have dependency violations but were not dumped
        /// during their own <see cref="PipExecutionPerformance"/> event (e.g., the related pip's
        /// perf event fired before the violation was reported).
        /// </summary>
        public override void Dispose()
        {
            if (!m_loggingErrorOccured)
            {
                foreach (var kvp in m_dependencyViolations)
                {
                    DumpPip(kvp.Key);
                }
            }

            base.Dispose();
        }

        /// <summary>
        /// This event will get data about reported file accesses and reported processes.
        /// The data will be added to <see cref="m_dynamicDataDictionary"/>, and will be dumped if the pip fails
        /// in the PipExecutionPerformance event.
        /// </summary>
        /// <param name="data"></param>
        public override void ProcessExecutionMonitoringReported(ProcessExecutionMonitoringReportedEventData data)
        {
            if (m_shouldDumpDynamicData && !ShouldSkipCollecting)
            {
                m_dynamicDataDictionary.TryAdd(data.PipId, data);
            }
        }

        /// <summary>
        /// Dumps pip data to a JSON file if it hasn't already been dumped and the log file limit hasn't been reached.
        /// Ensures that a log path is created, calls <see cref="o:DumpPipLiteAnalysisUtilities.DumpPip"/>, and updates
        /// the state of the analyzer if it runs into an error.
        /// </summary>
        /// <param name="pipId">ID of the pip to be dumped.</param>
        private void DumpPip(PipId pipId)
        {
            if (m_loggingErrorOccured)
            {
                return;
            }

            // Dedup: only dump each pip once
            if (!m_dumpedPips.TryAdd(pipId, 0))
            {
                return;
            }

            var currentNumLogFiles = Interlocked.Increment(ref m_numLogFilesGenerated);
            if (currentNumLogFiles > m_maxLogFiles)
            {
                if (currentNumLogFiles == m_maxLogFiles + 1)
                {
                    Logger.Log.RuntimeDumpPipLiteLogLimitReached(m_loggingContext, m_maxLogFiles);
                }

                return;
            }

            var pip = m_pipTable.HydratePip(pipId, PipQueryContext.DumpPipLiteAnalyzer);
            ProcessExecutionMonitoringReportedEventData? dynamicData = null;

            if (m_shouldDumpDynamicData)
            {
                m_dynamicDataDictionary.TryRemove(pipId, out dynamicData);
            }

            m_dependencyViolations.TryRemove(pipId, out var dependencyViolations);

            var dumpPipResult = false;

            if (!m_logPathCreated)
            {
                // A log entry should have been generated already if this fails
                m_logPathCreated = DumpPipLiteAnalysisUtilities.CreateLoggingDirectory(m_logPath.ToString(m_pipExecutionContext.PathTable), m_loggingContext);
            }

            if (m_logPathCreated)
            {
                // A log entry should have been generated already if this fails
                dumpPipResult = DumpPipLiteAnalysisUtilities.DumpPip(pip,
                                                                     dynamicData,
                                                                     m_logPath.ToString(m_pipExecutionContext.PathTable),
                                                                     m_pipExecutionContext.PathTable,
                                                                     m_pipExecutionContext.StringTable,
                                                                     m_pipExecutionContext.SymbolTable,
                                                                     m_pipGraph,
                                                                     m_loggingContext,
                                                                     dependencyViolations);
            }

            if (!(m_logPathCreated && dumpPipResult))
            {
                // This failure was already logged in DumpPipLiteAnalysisUtilies
                m_loggingErrorOccured = true;
            }
        }
    }
}
