// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated/>
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

namespace BuildXL.Cache.ContentStore.Hashing
{

    internal static class SR
    {
        // Fields
        internal const string Cryptography_PlatformNotSupported = "Cryptography_PlatformNotSupported";
    }
}
