.TH domino.sh 1 "" "" "Domino User Guide"
.SH NAME
domino.sh \- Run Domino on macOS
.SH SYNOPSIS
.B domino
[--domino-bin \fIdomino-dir\fR]
[--config \fIconfig-dsc-file\fR]
[--symlink-sdks-into \fIsdk-dir\fR]
[--check-kext-log]
[--load-kext | --no-load-kext]
[\fIdomino-arguments\fI]
.SH DESCRIPTION
A wrapper script for running Domino on macOS.
.SH OPTIONS
.TP
.BI --domino-bin " domino-dir"
Directory containing Domino binaries.  If not specified, defaults to the directory of the domino.sh script.
.TP
.BI --config " config-dsc-dir"
DominoScript main configuration file of the build (typically named 'config.dsc').  If omitted, no build is executed.
.TP
.BI --symlink-sdks-into " sdk-dir"
When specified, prior to running the build this script creates a symlink inside of the \fIsdk-dir\fR
folder pointing to the Sdk.Transformers folder from \fIdomino-dir\fR directory.  This is useful when
the build specification files require the "Transformers" sdk.
.TP
.BI --check-kext-log
When specified, after Domino build completes, this script will check the system log for any error messages
reported by DominoSandbox.
.TP
.BI --load-kext " | " --no-load-kext
Whether or not to attempt to load DominoSandbox kernel extension prior to running the build.  When neither 
is specified, the default is not to automatically load DominoSandbox.
.TP
.IB domino-arguments
Arbitrary arguments passed down to the Domino binary.