trigger: none  # Explicitly scheduled
parameters:
- name: type
  type: string
  default: Unofficial
  values:
  - Unofficial
  - Official

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - group: "BuildXL Common variables"
  - name: Codeql.Enabled
    value: false

extends:
  template: v1/1ES.${{ parameters.type }}.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        os: windows
      codeql:
        compiled:
          enabled: false
          justificationForDisabling: 'CodeQL would not be effective on this pipeline because builds are incremental and distributed. We have a dedicated pipeline for CodeQL.'
    
    pool:
      name: BuildXL-DevOpsAgents-Selfhost-BuildCache
      os: windows
      image: 1ESPT-Win2022-PME-3

    stages:
    - template: /.azdo/distributed/stage.yml@self
      parameters:
        buildXLVersion: Dogfood