// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using BuildXL.Cache.ContentStore.Hashing;
using Microsoft.Sbom.Contracts.Enums;
using Microsoft.Sbom.Contracts.Interfaces;
using System.Collections.Generic;
using System.IO;

namespace Tool.DropDaemon
{
    /// <summary>
    /// VSO hash algorithm.
    /// </summary>
    /// <remarks>
    /// This class was copied over from the dropvalidator repository before it was removed from there.
    /// Previously this came from the Microsoft.Parsers.ManifestGenerator package.
    /// Original file for reference (microsoft internal): https://github.com/microsoft/dropvalidator/blob/v3.8.11/Generators/ManifestGenerator/CBHashAlgorithmName.cs
    /// </remarks>
    public class VsoHashAlgorithmName : IAlgorithmNames
    {
        /// <summary>
        /// The VSO hash generated by BuildXL.
        /// </summary>
        public static AlgorithmName VSO => new AlgorithmName(nameof(VSO), stream => new ContentHash(HashType.Vso0, new BinaryReader(stream)).ToByteArray());

        /// <inheritdoc />
        public IList<AlgorithmName> GetAlgorithmNames() => new List<AlgorithmName> { VSO };
    }
}