trigger: none  # Triggered by PR policy

parameters:
- name: AdditionalBuildXLArgs
  type: string
  displayName: Additional BuildXL arguments for the full build
  default: ' '

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- group: "BuildXL Common variables"
- name: BuildXLDropName
  value: buildxl.pr.$(Build.BuildId)

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: Windows-SDL-Agents
      os: windows
    sdl:
      componentgovernance:
        # CODESYNC: .azdo/common/component-detection-exclusions.yml
        ignoreDirectories: 'Out/frontend/Download,Out/NodeJsForUnitTests'
      codeql:
        compiled:
          enabled: false
          justificationForDisabling: 'CodeQL is run in a separate dedicated pipeline.'

    stages:
    - stage: CB
      displayName: CloudBuild PR Validation
      jobs:
      - job: MinimalBuild
        displayName: Build minimal in CloudBuild
        timeoutInMinutes: 180
        templateContext:
          type: cloudBuildJob
          arguments:
            connectedServiceName: 2aef3ce3-3585-4f28-94a9-9b6cf2ff8dfe # CloudBuild Prod
            buildQueue: BuildXL_Internal_PR
            uploadDropMetadata: false
            additionalFlags: >-
              /f:spec='Public/Src/Deployment/buildXL.dsc'
              /p:[Sdk.BuildXL]microsoftInternal=1
              /validateCgManifestForNugets:cg\nuget\cgmanifest.json
              /cacheMiss+
              /q:ReleaseNet9
            sendEmail: false
            genericRunnerOptions: '{ "IsDropEnabled": "true", "DropName": "$(BuildXLDropName)", "ContentWriteMode": "WriteThrough" }'
            minBuilders: 2
            maxBuilders: 2
        pool:
          name: Windows-SDL-Agents
          os: windows

      - job: FullBuild
        displayName: Build all qualifiers in CloudBuild with new BuildXL
        timeoutInMinutes: 180
        dependsOn: MinimalBuild
        templateContext:
          type: cloudBuildJob
          arguments:
            connectedServiceName: 2aef3ce3-3585-4f28-94a9-9b6cf2ff8dfe # CloudBuild Prod
            buildQueue: BuildXL_Internal_PR
            uploadDropMetadata: false
            additionalFlags: >-
              /q:DebugNet8
              /q:ReleaseNet8
              /q:ReleaseDotNetCoreMac
              /q:ReleaseNet472
              /q:DebugNet472
              /q:DebugNet9
              /q:ReleaseNet9
              /p:[Sdk.BuildXL]microsoftInternal=1
              /enableEvaluationThrottling
              /validateCgManifestForNugets:cg\nuget\cgmanifest.json
              /p:[Sdk.BuildXL]enableRoslynAnalyzers=true
              /cacheMiss:[BuildXL_PR]
              /earlyWorkerRelease-
              /maxWorkersPerModule:0
              ${{ parameters.AdditionalBuildXLArgs }}
              /replayWarnings
            sendEmail: false
            genericRunnerOptions: '{"CodeCoverageOption":"DynamicChangeList"}'
            toolPaths: '{ "DominoEngine": "https://cloudbuild.artifacts.visualstudio.com/DefaultCollection/_apis/drop/drops/$(BuildXLDropName)?root=release/win-x64" }'
        pool:
          name: Windows-SDL-Agents
          os: windows
