// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.IO;
using BuildXL.Utilities;
using System.Diagnostics.ContractsLight;
using BuildXL.Cache.ContentStore.Hashing;
using System.Linq;
using System.Text;

namespace BuildXL.Ipc.ExternalApi.Commands
{
    /// <summary>
    /// Command corresponding to the <see cref="Client.GenerateBuildManifestFileList"/> API operation.
    /// </summary>
    public sealed class GenerateBuildManifestFileListCommand : Command<GenerateBuildManifestFileListResult>
    {
        /// <summary>
        /// DropName to identify which drop the Build Manifest is being generated for.
        /// </summary>
        public string DropName { get; }

        /// <nodoc />
        public GenerateBuildManifestFileListCommand(string dropName)
        {
            DropName = dropName;
        }

        /// <inheritdoc />
        public override bool TryParseResult(string result, out GenerateBuildManifestFileListResult commandResult)
        {
            return GenerateBuildManifestFileListResult.TryParse(result, out commandResult);
        }

        /// <inheritdoc />
        public override string RenderResult(GenerateBuildManifestFileListResult commandResult)
        {
            Contract.Requires(commandResult != null);

            return commandResult.Render();
        }

        internal override void InternalSerialize(BinaryWriter writer)
        {
            writer.Write(DropName);
        }

        internal static Command InternalDeserialize(BinaryReader reader)
        {
            return new GenerateBuildManifestFileListCommand(reader.ReadString());
        }
    }

    /// <summary>
    /// Stores Hash values and RelativePath of individual files added to drop
    /// </summary>
    public sealed class BuildManifestFileInfo : IEquatable<BuildManifestFileInfo>
    {
        /// <nodoc/>
        public string RelativePath { get; }

        /// <nodoc/>
        public ContentHash AzureArtifactsHash { get; }

        /// <nodoc/>
        public IReadOnlyList<ContentHash> BuildManifestHashes { get; }

        /// <nodoc/>
        public BuildManifestFileInfo(
            string relativePath,
            ContentHash azureArtifactsHash,
            IReadOnlyList<ContentHash> buildManifestHashes)
        {
            Contract.Requires(!string.IsNullOrEmpty(relativePath));
            Contract.Requires(azureArtifactsHash.IsValid);
            Contract.Requires(buildManifestHashes.All(h => h.IsValid));

            RelativePath = relativePath;
            AzureArtifactsHash = azureArtifactsHash;
            BuildManifestHashes = buildManifestHashes;
        }

        /// <summary>
        /// Separator used for serialization
        /// </summary>
        public const char Separator = '|';

        /// <summary>
        /// Number of fields to be serialized within BuildManifestFileInfo
        /// </summary>
        private const int MinFieldCount = 3;

        /// <summary>
        /// String representation format: RelativePath | AzureArtifactsHash | BuildManifestHash
        /// </summary>
        public override string ToString()
        {
            return $"{RelativePath}{BuildManifestFileInfo.Separator}{AzureArtifactsHash}{SerializeHashes(BuildManifestHashes)}";
        }

        private string SerializeHashes(IReadOnlyList<ContentHash> buildManifestHashes)
        {
            var sb = new StringBuilder();
            foreach (var hash in buildManifestHashes)
            {
                sb.Append(Separator);
                sb.Append(hash.ToString());
            }

            return sb.ToString();
        }

        /// <summary>
        /// Try to parse strings generated by <see cref="ToString"/>
        /// </summary>
        public static bool TryParse(string val, out BuildManifestFileInfo fileInfo)
        {
            fileInfo = null;

            var splits = val.Split(Separator);

            if (splits.Length < MinFieldCount)
            {
                return false;
            }

            var relativePath = splits[0];
            if (string.IsNullOrWhiteSpace(relativePath))
            {
                return false;
            }

            if (!ContentHash.TryParse(splits[1], out var azureArtifactsHash))
            {
                return false;
            }

            var manifestHashes = new List<ContentHash>(splits.Length - 2);
            foreach (var serializedHash in splits.Skip(2))
            {
                if (ContentHash.TryParse(serializedHash, out var hash))
                {
                    manifestHashes.Add(hash);
                }
                else
                {
                    return false;
                }
            }

            fileInfo = new BuildManifestFileInfo(
                relativePath,
                azureArtifactsHash,
                manifestHashes);

            return true;
        }

        /// <nodoc/>
        public bool Equals(BuildManifestFileInfo other)
        {
            return string.Equals(RelativePath, other?.RelativePath) &&
                string.Equals(AzureArtifactsHash, other?.AzureArtifactsHash) &&
                BuildManifestHashes.SequenceEqual(other?.BuildManifestHashes);
        }
    }

    /// <summary>
    /// Result of creating a build manifest file list for a drop
    /// </summary>
    public sealed class GenerateBuildManifestFileListResult
    {
        /// <summary>
        /// List of files added to drop. Returns null if the operation failed.
        /// </summary>
        public List<BuildManifestFileInfo> FileList { get; }

        /// <summary>
        /// The result of the operation
        /// </summary>
        public OperationStatus Status { get; }

        /// <summary>
        /// If the operation failed, describes the error; otherwise null.
        /// </summary>
        public string Error { get; }

        private GenerateBuildManifestFileListResult(OperationStatus status, List<BuildManifestFileInfo> fileList, string errorMessage)
        {
            FileList = fileList;
            Status = status;
            Error = errorMessage;
        }

        /// <nodoc />
        public static GenerateBuildManifestFileListResult CreateForSuccess(List<BuildManifestFileInfo> fileList)
        {
            Contract.Requires(fileList != null);

            return new GenerateBuildManifestFileListResult(OperationStatus.Success, fileList, null);
        }

        /// <nodoc />
        public static GenerateBuildManifestFileListResult CreateForFailure(OperationStatus status, string errorMessage)
        {
            Contract.Requires(!string.IsNullOrEmpty(errorMessage));
            Contract.Requires(status != OperationStatus.Success);

            return new GenerateBuildManifestFileListResult(status, null, errorMessage);
        }

        /// <nodoc />
        public string Render()
        {
            using var stringBuilderPoolInstance = Pools.StringBuilderPool.GetInstance();
            var sb = stringBuilderPoolInstance.Instance;

            sb.AppendLine($"{(byte)Status}");
            if (Status == OperationStatus.Success)
            {
                sb.AppendLine($"{FileList.Count}");

                foreach (BuildManifestFileInfo fileInfo in FileList)
                {
                    sb.AppendLine(fileInfo.ToString());
                }
            }
            else
            {
                sb.Append(Error);
            }

            return sb.ToString();
        }

        /// <nodoc />
        public static bool TryParse(string renderedResult, out GenerateBuildManifestFileListResult result)
        {
            using var reader = new StringReader(renderedResult);
            var statusValue = reader.ReadLine();
            if (!byte.TryParse(statusValue, out var status))
            {
                result = null;
                return false;
            }

            var operationStatus = (OperationStatus)status;
            if (!Enum.IsDefined(typeof(OperationStatus), operationStatus))
            {
                result = null;
                return false;
            }

            if (operationStatus == OperationStatus.Success)
            {
                var fileList = new List<BuildManifestFileInfo>();
                var count = reader.ReadLine();
                if (!int.TryParse(count, out var numberOfFiles))
                {
                    result = null;
                    return false;
                }

                for (int i = 0; i < numberOfFiles; i++)
                {
                    string val = reader.ReadLine();
                    if (!BuildManifestFileInfo.TryParse(val, out var buildManifestFileInfo))
                    {
                        result = null;
                        return false;
                    }

                    fileList.Add(buildManifestFileInfo);
                }

                result = CreateForSuccess(fileList);
            }
            else
            {
                var error = reader.ReadToEnd();
                result = CreateForFailure(operationStatus, error);
            }

            return true;
        }

        /// <nodoc />
        public enum OperationStatus : byte
        {
            /// <nodoc />
            Success,

            /// <nodoc />
            InternalError,

            /// <nodoc />
            UserError
        }
    }
}
