set BUILDXL_CACHE_DIRECTORY=%~dp0..\..\Out\Cache

IF NOT EXIST "%BUILDXL_CACHE_DIRECTORY%" (
	mkdir %BUILDXL_CACHE_DIRECTORY%
)

pushd %BUILDXL_CACHE_DIRECTORY%
set BUILDXL_CACHE_DIRECTORY=%CD%
popd