// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Linq;
using BuildXL.ToolSupport;

namespace SBOMConverter
{
    internal sealed class Args : CommandLineUtilities
    {
        public readonly string BcdeOutputPath = string.Empty;
        public readonly string ResultPath = string.Empty;

        private static readonly string[] s_helpStrings = new[] { "?", "help" };

        public Args(string[] args)
            : base(args)
        {
            foreach (Option opt in Options)
            {
                if (opt.Name.Equals("bcdeOutputPath", StringComparison.OrdinalIgnoreCase))
                {
                    BcdeOutputPath = ParseStringOption(opt);
                }
                else if (opt.Name.Equals("resultPath", StringComparison.OrdinalIgnoreCase))
                {
                    ResultPath = ParseStringOption(opt);
                }
                else if (s_helpStrings.Any(s => opt.Name.Equals(s, StringComparison.OrdinalIgnoreCase)))
                {
                    WriteHelp();
                }
            }

            if (string.IsNullOrEmpty(BcdeOutputPath))
            {
                throw Error("bcdeOutputPath must be specified.");
            }
        }

        private static void WriteHelp()
        {
            HelpWriter writer = new HelpWriter();
            writer.WriteBanner("SBOMConverter.exe - Wrapper tool to convert from the component detection package format to the SBOM package format.");
            writer.WriteOption("bcdeOutputPath", "Required. Path to the bcde-output.json file generated by the component detection tool.");
            writer.WriteOption("resultPath", "Required. Path to write the serialized results of the conversion in a JSON file.");
        }
    }
}
