# This pipeline does a clean build of the BuildXL repo as a distributed build
# The BuildXL version to download from drop and use for the build (e.g., 0.1.0-20221026.0)
# should be specified via the queue-time variable $(BuildXLPackageVersion) 
trigger: none   # This pipeline is explicitly scheduled

resources:
  repositories:
  # 08/07/25: Temporarily pointing to latest main instead of 1ESPT release 
  #           to unblock broken pipeline
  # - repository: 1esPipelines
  #   type: git
  #   name: 1ESPipelineTemplates/1ESPipelineTemplates
  #   ref: refs/tags/release
  - repository: 1esPipelines
    type: git
    name: Domino/1ESPipelines
    ref: refs/heads/main

variables:
  - group: "BuildXL Common variables"
  - name: Codeql.Enabled
    value: false

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        os: windows
      codeql:
        compiled:
          enabled: false
          justificationForDisabling: 'CodeQL would not be effective on this pipeline because builds are incremental and distributed. We have a dedicated pipeline for CodeQL.'
    
    pool:
      name: BuildXL-DevOpsAgents-Selfhost-BuildCache
      os: windows
      image: 1ESPT-Win2022-PME-3

    stages:
    - template: /.azdo/distributed/stage.yml@self
      parameters:
        buildXLVersion: $(BuildXLPackageVersion)
  