// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Collections.Generic;

namespace BuildXL.Visualization.Models
{
    /// <summary>
    /// Spec Details
    /// </summary>
    public sealed class SpecDetails : FileReference
    {
        /// <summary>
        /// List of pips generated by spec file
        /// </summary>
        public IEnumerable<PipReference> GeneratedPips { get; set; }

        /// <summary>
        /// List of values in spec
        /// </summary>
        public IEnumerable<ValueReference> Values { get; set; }
    }
}
