# Agent-based CloudTest task example
# Docs: https://eng.ms/docs/more/developer-guides/cloudtest-user-guide/cloudtest/how-tos/setup-cloudtest-azuredevops-tasks
# Fileless TestMap: https://eng.ms/docs/cloud-ai-platform/developer-services/one-engineering-system-1es/cloudtest-user-guide/cloudtest/features/fileless-testmap

trigger: none

parameters:
  - name: connectedServiceName
    type: string
    default: 'CloudTest-BuildXL-Prod'
  - name: cloudTestTenant
    type: string
    default: 'cloudtest-sample'
  - name: sessionTimeout
    type: number
    default: 120
  - name: ServiceConnection
    type: string
    default: 'mseng-Domino-BuildXL-Pipelines' # Service connection used by most BuildXL pipelines that need an authentication token
  - name: Resource
    type: string
    default: '499b84ac-1321-427f-aa17-267ca6975798' # Azure DevOps resource UUID
  - name: AccessTokenVariable
    type: string
    default: 'GeneratedAccessToken' # Name of the pipeline variable that will store the generated access token
  - name: CloudTestResource
    type: string
    default: '77c466d9-b133-4a83-a8f5-c94133051e06' # CloudTest API resource ID
  - name: CloudTestTokenVariable
    type: string
    default: 'CloudTestAccessToken' # Name of the pipeline variable that will store the CloudTest bearer token

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool: 
      name: BuildXL-DevOpsAgents-Selfhost-BuildCache
      image: ubuntu-24.04-PME-GPT
      os: linux
      vhd: 
        enabled: false
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        os: windows
    stages:
    - stage: BuildXL
      dependsOn: []
      displayName: BuildXL-CloudTest
      jobs:
      - job: build
        displayName: Build JS repo
        templateContext:
          workflow: BuildXL   
          preBuildSteps:
          - task: microsoft-1es-production.entra-authenticate.entra-authenticate.EntraAuthenticate@0
            displayName: '🪙 Acquire access token for ${{ parameters.ServiceConnection }}'
            inputs:
              azureSubscription: ${{ parameters.ServiceConnection }}
              resource: ${{ parameters.Resource }}
              secretVariable: ${{ parameters.AccessTokenVariable }}
          - task: microsoft-1es-production.entra-authenticate.entra-authenticate.EntraAuthenticate@0
            displayName: '🪙 Acquire CloudTest bearer token'
            inputs:
              azureSubscription: ${{ parameters.ServiceConnection }}
              resource: ${{ parameters.CloudTestResource }}
              secretVariable: ${{ parameters.CloudTestTokenVariable }}
          - task: UseDotNet@2
            inputs:
              packageType: "sdk"
              version: "9.x"
            displayName: "Install .NET 9 SDK"
          - task: NodeTool@0
            inputs:
              versionSpec: '22.18.0'
            displayName: 'Install Node'
          - script: |
              npm config set registry https://cloudbuild.pkgs.visualstudio.com/_packaging/BuildXL.Selfhost/npm/registry/
              npm config set //cloudbuild.pkgs.visualstudio.com/_packaging/BuildXL.Selfhost/npm/registry/:_authToken=$FEED_TOKEN
              npm install -g yarn
            displayName: 'Install Yarn'
            env:
              FEED_TOKEN: $(${{ parameters.AccessTokenVariable }})
          - script: yarn install
            displayName: 'Yarn Install'
            workingDirectory: $(Build.SourcesDirectory)/Examples/CloudTest
          # Build BuildXL minimal and deploy to dev so the main build step uses the locally-built engine. We can drop this step
          # once the required BuildXL changes are checked in
          - bash: |
              set -eu
              bash bxl.sh --internal --minimal --deploy-dev --release
            displayName: 'Build BXL (minimal + deploy dev)'
            workingDirectory: $(Build.SourcesDirectory)
            env:
              PAT1esSharedAssets: $(${{ parameters.AccessTokenVariable }})
              PATCloudBuild: $(${{ parameters.AccessTokenVariable }})
              VSTSPERSONALACCESSTOKEN: $(System.AccessToken)
          buildXL:
            install: false
            # Use the just built engine
            invocationPrefix: /mnt/vss/_work/1/s/Out/Bin/release/linux-x64/AdoBuildRunner
            arguments: >-
              /c:config.dsc
              /logOutput:FullOutputAlways
              /p:CloudTestTokenVariableName=${{ parameters.CloudTestTokenVariable }}
            workingDirectory: $(Build.SourcesDirectory)/Examples/CloudTest
            env:
              ${{ parameters.CloudTestTokenVariable }}: $(${{ parameters.CloudTestTokenVariable }})