// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using BuildXL.Utilities.CodeGenerationHelper;
using Microsoft.CodeAnalysis;
using System.Globalization;
using EventGenerators = BuildXL.Utilities.Instrumentation.Common.Generators;
using System.Diagnostics.ContractsLight;

namespace BuildXL.LogGen.Core
{
    /// <summary>
    /// Set of functions for creating an auto generated log file.
    /// </summary>
    public static class LogWriterHelpers
    {
        private const string GlobalInstrumentationNamespace = "global::BuildXL.Utilities.Instrumentation.Common";
        private const string NotifyContextWhenErrorsAreLogged = "m_notifyContextWhenErrorsAreLogged";
        private const string NotifyContextWhenWarningsAreLogged = "m_notifyContextWhenWarningsAreLogged";

        /// <summary>
        /// Generates the requested log classes using the provided code generator.
        /// </summary>
        /// <returns>Number of classes written</returns>
        public static int WriteLogToStream(IReadOnlyList<LoggingClass> loggingClasses, CodeGenerator gen, string namespaceValue, string targetFramework, string targetRuntime, ref List<GeneratorBase> generators, ErrorReport errorReport)
        {
            var itemsWritten = 0;

            gen.Ln("// <auto-generated/>\r\n");
            gen.Ln();
            gen.Ln("#nullable enable");
            gen.Ln();

            Dictionary<LoggingSite, List<GeneratorBase>> generatorMap = CreateGenerators(loggingClasses, gen, namespaceValue, targetFramework, targetRuntime, ref generators, errorReport);

            foreach (var loggingClass in loggingClasses)
            {
                itemsWritten++;
                gen.Ln("namespace {0}", loggingClass.Symbol.ContainingNamespace);
                using (gen.Br)
                {
                    // Figure out the namespaces needed
                    IDictionary<string, HashSet<string>> namespacesWithConditions = CombineNamespaces(generators);
                    foreach (var namespacesWithCondition in namespacesWithConditions)
                    {
                        bool hasCondition = !string.IsNullOrEmpty(namespacesWithCondition.Key);
                        if (hasCondition)
                        {
                            gen.Ln("#if {0}", namespacesWithCondition.Key);
                        }
                        else
                        {
                            namespacesWithCondition.Value.Add(namespaceValue);
                        }

                        foreach (var ns in namespacesWithCondition.Value)
                        {
                            gen.Ln("using {0};", ns);
                        }

                        if (hasCondition)
                        {
                            gen.Ln("#endif");
                        }
                    }

                    gen.Ln();
                    gen.Ln("#pragma warning disable 219");
                    gen.Ln();

                    GenerateInterface(gen, loggingClass, errorReport);
                    if (loggingClass.InstanceBasedLogging)
                    {
                        GenerateStaticLogMethods(gen, loggingClass, generatorMap, errorReport);
                    }
                    else
                    {
                        GenerateLoggerInstance(gen, loggingClass, generatorMap, errorReport);
                    }

                    GenerateImplementations(gen, loggingClass, generatorMap, errorReport, generators);
                }
            }

            foreach (GeneratorBase generator in generators)
            {
                gen.Ln();
                generator.GenerateClass();
            }

            return itemsWritten;
        }

        private static void GenerateInterface(CodeGenerator gen, LoggingClass loggingClass, ErrorReport errorReport)
        {
            gen.GenerateSummaryComment("Logger interface");
            gen.WriteGeneratedAttribute(includeCodeCoverageExclusion: false);
            gen.Ln($"{GetAccessibilityString(loggingClass.Symbol.DeclaredAccessibility, errorReport)} interface {loggingClass.InterfaceName} : {GlobalInstrumentationNamespace}.ILogger");
            using (gen.Br)
            {
                // Log methods
                foreach (var site in loggingClass.Sites)
                {
                    gen.GenerateSummaryComment($"({site.Level}) - {new XText(site.SpecifiedMessageFormat).ToString()}");
                    gen.Ln($"void {site.Method.Name}( {GenerateParameterString(site, includeContext: true)});");
                    gen.Ln();
                }
            }
        }

        private static void GenerateLoggerInstance(CodeGenerator gen, LoggingClass loggerClass, Dictionary<LoggingSite, List<GeneratorBase>> generatorMap, ErrorReport errorReport)
        {
            var className = "Log";
            gen.GenerateSummaryComment("Instance based logger");
            gen.WriteGeneratedAttribute();
            gen.Ln($"{GetAccessibilityString(loggerClass.Symbol.DeclaredAccessibility, errorReport)} class {className}");
            using (gen.Br)
            {
                gen.GenerateSummaryComment("The static logger this delegates to");
                gen.Ln($"private {loggerClass.Symbol.Name} m_logger;");
                gen.Ln();

                gen.GenerateSummaryComment("The logging context to use.");
                gen.Ln($"public {GlobalInstrumentationNamespace}.LoggingContext LoggingContext {{ get; }}");
                gen.Ln();

                gen.GenerateSummaryComment("Creates a new instnce base logger.");
                gen.Ln($"public Log({GlobalInstrumentationNamespace}.LoggingContext loggingContext, bool preserveLogEvents = false)");
                using (gen.Br)
                {
                    gen.Ln($"m_logger = {loggerClass.Symbol.Name}.CreateLogger(preserveLogEvents);");
                    gen.Ln("LoggingContext = loggingContext;");
                }

                foreach (LoggingSite site in loggerClass.Sites)
                {
                    List<GeneratorBase> generators = generatorMap[site];

                    gen.GenerateSummaryComment(site.GetDocComment());

                    gen.Ln($"{GetAccessibilityString(site.Method.DeclaredAccessibility, errorReport)} void {site.Method.Name}({GenerateParameterString(site, includeContext: true)})");
                    using (gen.Br)
                    {
                        gen.Ln($"m_logger.{site.Method.Name}({GenerateArgumentString(site, includeContext: true)});");
                    }
                    gen.Ln();
                }
            }
        }

        private static void GenerateStaticLogMethods(CodeGenerator gen, LoggingClass loggingClass, Dictionary<LoggingSite, List<GeneratorBase>> generatorMap, ErrorReport errorReport)
        {
            var symbol = loggingClass.Symbol;
            gen.Ln("namespace Logger");
            using (gen.Br)
            {
                gen.GenerateSummaryComment("Static Logging class");
                gen.WriteGeneratedAttribute();
                gen.Ln($"{GetAccessibilityString(symbol.DeclaredAccessibility, errorReport)} static class Log");
                using (gen.Br)
                {
                    foreach (LoggingSite site in loggingClass.Sites)
                    {
                        List<GeneratorBase> generators = generatorMap[site];

                        gen.GenerateSummaryComment(site.GetDocComment());

                        gen.Ln($"{GetAccessibilityString(site.Method.DeclaredAccessibility, errorReport)} static void {site.Method.Name}({GenerateParameterString(site, includeContext: true)})");
                        using (gen.Br)
                        {
                            if (loggingClass.EmitDebuggingInfo)
                            {
                                gen.Ln($"if ({site.LoggingContextParameterName}.Logger as {loggingClass.InterfaceName} == null)");
                                using (gen.Br)
                                {
                                    gen.Ln("System.Diagnostics.Debugger.Launch();");
                                }
                                gen.Ln();
                            }

                            gen.Ln($"(({loggingClass.InterfaceName}){site.LoggingContextParameterName}.Logger!).{site.Method.Name}({GenerateArgumentString(site, includeContext: true)});");
                        }
                        gen.Ln();
                    }
                }
            }
        }

        private static void GenerateImplementations(CodeGenerator gen, LoggingClass loggingClass, Dictionary<LoggingSite, List<GeneratorBase>> generatorMap, ErrorReport errorReport, List<GeneratorBase> generators)
        {
            var symbol = loggingClass.Symbol;
            var useInstanceBasedLogging = loggingClass.InstanceBasedLogging;
            gen.GenerateSummaryComment("Logging Instantiation");
            gen.WriteGeneratedAttribute();
            if (useInstanceBasedLogging)
            {
                gen.Ln($"{GetAccessibilityString(symbol.DeclaredAccessibility, errorReport)} class {loggingClass.Name} : {GlobalInstrumentationNamespace}.LoggerBase, {loggingClass.InterfaceName}");
            }
            else
            {
                gen.Ln(
                    "{0} partial class {1} : {2}.LoggerBase",
                    GetAccessibilityString(symbol.DeclaredAccessibility, errorReport),
                    symbol.Name,
                    GlobalInstrumentationNamespace);
            }
            using (gen.Br)
            {
                if (!useInstanceBasedLogging)
                {
                    gen.Ln("static private Logger m_log = new {0}Impl();", symbol.Name);
                    gen.Ln();

                    gen.GenerateSummaryComment("Factory method that creates instances of the logger.");
                    gen.Ln($"public static {symbol.Name} CreateLogger(bool preserveLogEvents = false)");
                    using (gen.Br)
                    {
                        gen.Ln($"return new {symbol.Name}Impl");
                        using (gen.Br)
                        {
                            gen.Ln("PreserveLogEvents = preserveLogEvents,");
                            gen.Ln("InspectMessageEnabled = preserveLogEvents,");
                        }
                        gen.Ln(";");
                    }
                    gen.Ln();

                    gen.GenerateSummaryComment("Factory method that creates instances of the logger that tracks errors and allows for observers");
                    gen.Ln($"public static {symbol.Name} CreateLoggerWithTracking(bool preserveLogEvents = false)");
                    using (gen.Br)
                    {
                        gen.Ln($"return new {symbol.Name}Impl");
                        using (gen.Br)
                        {
                            gen.Ln("PreserveLogEvents = preserveLogEvents,");
                            gen.Ln("InspectMessageEnabled = true,");
                        }
                        gen.Ln(";");
                    }
                    gen.Ln();
                }

                var notifyContextWhenErrorsAreLoggedIsUsed = false;
                var notifyContextWhenWarningsAreLoggedIsUsed = false;

                foreach (GeneratorBase generator in generators)
                {
                    generator.GenerateAdditionalLoggerMembers();
                }

                if (!useInstanceBasedLogging)
                {
                    gen.GenerateSummaryComment("Logging implementation");
                    gen.WriteGeneratedAttribute();
                    gen.Ln("private class {0}Impl: {0}", symbol.Name);
                }
                using (useInstanceBasedLogging ? null : gen.Br)
                {
                    foreach (LoggingSite site in loggingClass.Sites)
                    {
                        List<GeneratorBase> mappedGenerators = generatorMap[site];

                        gen.GenerateSummaryComment("Logging implementation");

                        var parametersWithContext = GenerateParameterString(site, includeContext: true);
                        if (useInstanceBasedLogging)
                        {
                            gen.Ln($"public void {site.Method.Name}({parametersWithContext})");
                        }
                        else
                        {
                            gen.Ln($"{GetAccessibilityString(site.Method.DeclaredAccessibility, errorReport)} override void {site.Method.Name}({parametersWithContext})");
                        }
                        using (gen.Br)
                        {
                            var argsWithContext = GenerateArgumentString(site, includeContext: true);
                            var argsWithoutContext = GenerateArgumentString(site, includeContext: true);

                            if (site.Level == BuildXL.Utilities.Instrumentation.Common.Level.Critical)
                            {
                                // Critical events are always logged synchronously
                                gen.Ln($"{site.Method.Name}_Core({argsWithContext});");
                            }
                            else
                            {
                                gen.Ln($"if ({site.LoggingContextParameterName}.{nameof(BuildXL.Utilities.Instrumentation.Common.LoggingContext.IsAsyncLoggingEnabled)})");
                                using (gen.Br)
                                {
                                    // NOTE: This allocates a closure for every log message when async logging is enabled.
                                    // This is assumed to not be non-issue as the logging infrastructure already has many allocations
                                    // as a part of logging so this allocation doesn't 
                                    gen.Ln($"EnqueueLogAction({site.LoggingContextParameterName}, {site.Id}, () => {site.Method.Name}_Core({argsWithContext}));");
                                }
                                gen.Ln("else");
                                using (gen.Br)
                                {
                                    gen.Ln($"{site.Method.Name}_Core({argsWithContext});");
                                }
                            }

                            // Register errors on the logging context so code can assert that errors were logged
                            if (site.Level == BuildXL.Utilities.Instrumentation.Common.Level.Error)
                            {
                                notifyContextWhenErrorsAreLoggedIsUsed = true;
                                gen.Ln($"if ({NotifyContextWhenErrorsAreLogged})");
                                using (gen.Br)
                                {
                                    gen.Ln($"{site.LoggingContextParameterName}.SpecifyErrorWasLogged({site.Id});");
                                }
                            }

                            // Register warnings on the logging context so code can assert that warnings were logged
                            if (site.Level == BuildXL.Utilities.Instrumentation.Common.Level.Warning)
                            {
                                notifyContextWhenWarningsAreLoggedIsUsed = true;
                                gen.Ln($"if ({NotifyContextWhenWarningsAreLogged})");
                                using (gen.Br)
                                {
                                    gen.Ln($"{site.LoggingContextParameterName}.SpecifyWarningWasLogged();");
                                }
                            }
                        }

                        gen.Ln();
                        gen.Ln($"private void {site.Method.Name}_Core({parametersWithContext})");
                        using (gen.Br)
                        {
                            List<char> interceptedCode = new List<char>();
                            using (gen.InterceptOutput((c) => interceptedCode.Add(c)))
                            {
                                foreach (GeneratorBase generator in mappedGenerators)
                                {
                                    generator.GenerateLogMethodBody(
                                        site,
                                        getMessageExpression: () =>
                                        {
                                            // Track whether the getMessage() function was called where there is a format string
                                            if (site.GetMessageFormatParameters().Any())
                                            {
                                                // Only InspecMessage takes a fully constructed message.
                                                // To avoid redundant allocations this callback creates
                                                // an argument instead of creating a local variable.
                                                return
                                                    string.Format(
                                                        CultureInfo.InvariantCulture,
                                                        "string.Format(System.Globalization.CultureInfo.InvariantCulture, \"{0}\", {1})",
                                                        site.GetNormalizedMessageFormat(),
                                                        string.Join(", ", site.GetMessageFormatParameters()));
                                            }

                                            return "\"" + site.SpecifiedMessageFormat + "\"";
                                        });
                                }
                            }

                            // Now we can write out the intercepted code from the code generators
                            foreach (char c in interceptedCode)
                            {
                                gen.Output(c);
                            }
                        }

                        gen.Ln();
                    }
                }

                if (notifyContextWhenErrorsAreLoggedIsUsed)
                {
                    gen.Ln($"private bool {NotifyContextWhenErrorsAreLogged} = true;");
                }

                if (notifyContextWhenWarningsAreLoggedIsUsed)
                {
                    gen.Ln($"private bool {NotifyContextWhenWarningsAreLogged} = true;");
                }
            }
        }

        private static string GenerateParameterString(LoggingSite site, bool includeContext)
        {
            var contextParameter = includeContext
                ? $"{GlobalInstrumentationNamespace}.LoggingContext {site.LoggingContextParameterName}" + (site.Payload.Any() ? ", " : string.Empty)
                : string.Empty;

            return contextParameter + string.Join(", ", site.Payload.Select(
                parameter =>
                {
                    var modifier = parameter.RefKind == RefKind.Ref ? "ref" : string.Empty;
                    var typeValue = parameter.Type.ToDisplayString();
                    var defaultValue = parameter.HasExplicitDefaultValue
                        ? " = " + (parameter.ExplicitDefaultValue == null ? "null" : parameter.ExplicitDefaultValue.ToString())
                        : string.Empty;
                    return $"{modifier}{typeValue} {parameter.Name}{defaultValue}";
                })
            );
        }

        private static string GenerateArgumentString(LoggingSite site, bool includeContext)
        {
            var contextArgument = includeContext
               ? site.LoggingContextParameterName + (site.Payload.Any() ? ", " : string.Empty)
               : string.Empty;

            return contextArgument + string.Join(", ", site.Payload.Select(
                parameter =>
                {
                    var modifier = parameter.RefKind == RefKind.Ref ? "ref" : string.Empty;
                    return $"{modifier} {parameter.Name}";
                })
            );
        }

        /// <summary>
        /// Creates a mapping of logging site to the generators that must run for it
        /// </summary>
        private static Dictionary<LoggingSite, List<GeneratorBase>> CreateGenerators(IReadOnlyList<LoggingClass> loggingClasses, CodeGenerator codeGenerator, string namespaceValue, string targetFramework, string targetRuntime, ref List<GeneratorBase> generators, ErrorReport errorReport)
        {
            Dictionary<EventGenerators, GeneratorBase> generatorsByName = new Dictionary<EventGenerators, GeneratorBase>();
            Dictionary<LoggingSite, List<GeneratorBase>> generatorsBySite = new Dictionary<LoggingSite, List<GeneratorBase>>();

            foreach (var loggingClass in loggingClasses)
            {
                foreach (var site in loggingClass.Sites)
                {
                    List<GeneratorBase> generatorsPerSite = new List<GeneratorBase>();

                    foreach (EventGenerators gen in Enum.GetValues(typeof(EventGenerators)))
                    {
                        if (gen == EventGenerators.None)
                        {
                            continue;
                        }

                        if ((site.EventGenerators & gen) != 0)
                        {
                            GeneratorBase generator;
                            if (generatorsByName.TryGetValue(gen, out generator))
                            {
                                generatorsPerSite.Add(generator);
                            }
                            else
                            {
                                Func<GeneratorBase> generatorFactory;
                                if (!global::BuildXL.LogGen.Generators.SupportedGenerators.Generators.TryGetValue(gen, out generatorFactory))
                                {
                                    // AriaV2Disabled is the only generator that's allow to be specified with not actual
                                    // generator existing
                                    if (gen != EventGenerators.AriaV2Disabled)
                                    {
                                        Contract.Assert(false, "Failed to find a generator for " + gen.ToString() +
                                            ". This should have been caught in Parsing");
                                    }
                                    continue;
                                }

                                generator = generatorFactory();
                                generator.Initialize(namespaceValue, targetFramework, targetRuntime, codeGenerator, loggingClasses, errorReport);
                                generatorsByName.Add(gen, generator);
                                generatorsPerSite.Add(generator);
                            }
                        }
                    }

                    generatorsBySite[site] = generatorsPerSite;
                }
            }

            generators = new List<GeneratorBase>(generatorsByName.Values);

            return generatorsBySite;
        }

        private static IDictionary<string, HashSet<string>> CombineNamespaces(List<GeneratorBase> generators)
        {
            IDictionary<string, HashSet<string>> namespacesWithConditions = new Dictionary<string, HashSet<string>>();

            foreach (GeneratorBase generator in generators)
            {
                foreach (var ns in generator.ConsumedNamespaces)
                {
                    HashSet<string> namespaces;
                    if (!namespacesWithConditions.TryGetValue(ns.Item2, out namespaces))
                    {
                        namespaces = new HashSet<string>();
                        namespacesWithConditions[ns.Item2] = namespaces;
                    }

                    namespaces.Add(ns.Item1);
                }
            }

            return namespacesWithConditions;
        }

        private static string GetAccessibilityString(Accessibility accessibility, ErrorReport errorReport)
        {
            switch (accessibility)
            {
                case Accessibility.Private:
                    return "private";
                case Accessibility.Protected:
                    return "protected";
                case Accessibility.Internal:
                    return "internal";
                case Accessibility.Public:
                    return "public";
                default:
                    errorReport.ReportError("Unsupported accessibility type: {0}", accessibility);
                    return null;
            }
        }
    }
}
