parameters:
# Do not use this parameter, and rather BxlExtraArgs below to append extra arguments.
# This parameters is used as a constant to define arguments for all Linux builds below
- name: BxlCommonArgs
  type: string
  default: >-
    /logObservedFileAccesses 
    /logoutput:FullOutputOnError 
    /p:[Sdk.BuildXL]xunitSemaphoreCount=8 
    /forceAddExecutionPermission-

- name: BxlExtraArgs
  type: string
  default: ''

- name: pool
  type: object

- name: sdkVersion
  type: string
  default: '9.x'

# Pre-build steps, including downloading BuildXL if needed
- name: preBuildSteps
  type: stepList
  default: []

stages:
# This stage must run under Ubuntu 22.04 or newer for compatibility reasons when building the eBPF Sandbox.
# This is why the pool parameter is not passed along here, and specified in job-ebpf.yml itself
- stage: Bootstrap_Internal_eBPF
  displayName: Bootstrap eBPF Sandbox Internal
  dependsOn: []
  jobs:
  # Build the eBPF Sandbox binaries first for the next step to consume.
  - template: /.azdo/linux/jobs/job-ebpf.yml@self
    parameters:
      BxlCommonArgs: --shared-comp ${{ parameters.BxlCommonArgs }} ${{ parameters.BxlExtraArgs }}
      internal: true
      outputArtifactName: 'ebpf-dev-internal'
      sdkVersion: ${{ parameters.sdkVersion }}

# This stage may run on an older version of Ubuntu such as 20.04
# It's necessary for the interpose sandbox to be built on Ubuntu 20.04 to maintain compatibility with older versions of glibc.
- stage: Bootstrap_Internal
  displayName: Bootstrap engine for validations
  dependsOn: [Bootstrap_Internal_eBPF]
  jobs:
  # Build and test selfhost with BuildXL
  - template: /.azdo/linux/jobs/job-bootstrap.yml@self
    parameters:
      BxlCommonArgs: --shared-comp /p:BuildXLEbpfSandboxDeploymentOverridePath=$(Build.StagingDirectory)/Linux.eBPF ${{ parameters.BxlCommonArgs }} ${{ parameters.BxlExtraArgs }}
      pool: ${{ parameters.pool }}
      sdkVersion: ${{ parameters.sdkVersion }}
      preBuildSteps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download eBPF Sandbox binaries'
        inputs:
          artifactName: 'ebpf-dev-internal'
          targetPath: "$(Build.StagingDirectory)/Linux.eBPF"

- stage: Bootstrap_External_eBPF
  displayName: Bootstrap eBPF Sandbox External
  dependsOn: []
  jobs:
  # Build the eBPF Sandbox binaries first for the next step to consume.
  - template: /.azdo/linux/jobs/job-ebpf.yml@self
    parameters:
      BxlCommonArgs: --shared-comp ${{ parameters.BxlCommonArgs }} ${{ parameters.BxlExtraArgs }}
      internal: false
      outputArtifactName: 'ebpf-dev-external'
      sdkVersion: ${{ parameters.sdkVersion }}

- stage: Build_External
  displayName: External validation
  dependsOn: [Bootstrap_External_eBPF]
  jobs:
    - template: /.azdo/linux/jobs/job-external.yml@self
      parameters:
        BxlCommonArgs: --shared-comp /p:BuildXLEbpfSandboxDeploymentOverridePath=$(Build.StagingDirectory)/Linux.eBPF ${{ parameters.BxlCommonArgs }} ${{ parameters.BxlExtraArgs }}
        pool: ${{ parameters.pool }}
        sdkVersion: ${{ parameters.sdkVersion }}
        preBuildSteps:
        - task: DownloadPipelineArtifact@2
          displayName: 'Download eBPF Sandbox binaries'
          inputs:
            artifactName: 'ebpf-dev-external'
            targetPath: "$(Build.StagingDirectory)/Linux.eBPF"

- stage: Build_Internal
  displayName: Internal validation
  dependsOn: Bootstrap_Internal
  jobs:
  - template: /.azdo/linux/jobs/job-selfhost.yml@self
    parameters:
      BxlCommonArgs: --shared-comp ${{ parameters.BxlCommonArgs }} ${{ parameters.BxlExtraArgs }}
      pool: ${{ parameters.pool }}
      sdkVersion: ${{ parameters.sdkVersion }}
      preBuildSteps:
      - ${{ each step in parameters.preBuildSteps }}:
        - ${{ step }}

- stage: Verify_PTrace
  displayName: PTrace validation
  dependsOn: Bootstrap_Internal  
  jobs:
  - template: /.azdo/linux/jobs/job-ptrace.yml@self
    parameters:
      BxlCommonArgs: ${{ parameters.BxlCommonArgs }} ${{ parameters.BxlExtraArgs }}
      pool: ${{ parameters.pool }}
      sdkVersion: ${{ parameters.sdkVersion }}

- stage: Build_Distributed
  displayName: Distributed test
  dependsOn: [Build_Internal, Verify_PTrace] 
  jobs:
  - template: /.azdo/linux/jobs/job-distributed-1espt.yml@self
    parameters:
      pool:
        # This stage expects a pool with a build cache configured, so harcoding that one
        ${{ each kvp in parameters.pool }}:
          ${{ if not(in(kvp.key, 'name')) }}:
            ${{ kvp.key }}: ${{ kvp.value }}
        name: BuildXL-DevOpsAgents-Selfhost-BuildCache
      preBuildSteps:
      - ${{ each step in parameters.preBuildSteps }}:
        - ${{ step }}