trigger: none

# Base pipeline for Linux PR validations.
# Extended by run-on-ubuntu-2204.yml, run-on-ubuntu-2404.yml, and run-on-azure-linux-3.yml,
# which are the entrypoints to the corresponding pipelines.
parameters:
- name: image
  type: string
- name: BxlExtraArgs
  type: string

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool: 
      name: BuildXL-DevOpsAgents-Selfhost-BuildCache
      image: ${{ parameters.image }}
      os: linux
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        os: windows

    stages:
    - template: /.azdo/linux/linux-stages-template.yml
      parameters:
        pool:
          name: BuildXL-DevOpsAgents-Selfhost-BuildCache
          image: ${{ parameters.image }}
          os: linux
        BxlExtraArgs: ${{ parameters.BxlExtraArgs }}
