trigger: none  # Explicitly scheduled for PRs

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

parameters:
- name: BuildSelfhost
  type: boolean
  default: true

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: BuildXL-DevOpsAgents-Linux-PME
      os: linux
    sdl:
      sourceAnalysisPool:
        name: 1ES-Shared-Hosted-Pool_Windows-Server-2022
        os: windows

    stages:
    - stage: Build
      jobs:
      # Build and test selfhost with BuildXL
      - ${{ if parameters.BuildSelfhost }}:
        - template: /.azdo/linux/job-selfhost.yml@self
          parameters:
            ValidationName: PublicRelease
            BxlExtraArgs: /q:ReleaseLinux

        - template: /.azdo/linux/job-selfhost.yml@self
          parameters:
            ValidationName: InternalRelease
            BxlExtraArgs: --internal /q:ReleaseLinux
