trigger: none  # Explicitly scheduled for PRs

parameters:
- name: BxlCommonArgs
  type: string
  # We pass xunit semaphore `/p:[Sdk.BuildXL]xunitSemaphoreCount=8` to limit the number of parallel xunit pips.
  # Too many xunit pips running in parallel can cause the long running ones to hang. 
  default: '
    /logObservedFileAccesses 
    /logoutput:FullOutputOnError 
    /p:[Sdk.BuildXL]xunitSemaphoreCount=8 
    /forceAddExecutionPermission-
    /p:BuildXLDumpOpenFilesOnDescriptorSpike=1
  '
- name: pool
  type: object
  default: 
    name: BuildXL-DevOpsAgents-Selfhost-BuildCache
    image: ubuntu-22.04-PME-GPT
    os: linux
    
resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: Domino/1ESPipelines
    ref: refs/heads/main
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
  parameters:
    pool: ${{ parameters.pool }}
    sdl:
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        image: Windows-SDL-Image
        os: windows

    stages:
    - template: /.azdo/linux/linux-stages-template.yml
      parameters:
        pool: ${{ parameters.pool }}
        BxlCommonArgs: ${{ parameters.BxlCommonArgs }}