trigger: none  # Explicitly scheduled for PRs

extends:
  template: /.azdo/linux/pipeline_base.yml@self
  parameters:
    image: ubuntu-24.04-PME-GPT
    BxlExtraArgs: /p:BUILDXL_FINGERPRINT_SALT=Ubuntu2404