trigger: none  # Explicitly scheduled for PRs

extends:
  template: /.azdo/linux/pipeline_base.yml@self
  parameters:
    image: 1es-pt-azurelinux3-v2
    BxlExtraArgs: /p:BUILDXL_FINGERPRINT_SALT=AzureLinux3
