trigger: none  # Explicitly scheduled for PRs

extends:
  template: /.azdo/linux/pipeline_base.yml@self
  parameters:
    image: ubuntu-22.04-PME-GPT
    # We keep using interpose for Ubuntu 22.04 as test coverage until we can retire the interpose sandbox.
    BxlExtraArgs: /p:BUILDXL_FINGERPRINT_SALT=Ubuntu2204 /enableLinuxEBPFSandbox-
