trigger: none  # Explicitly scheduled for PRs

variables:
# Add CG exclusions
- template: /.azdo/common/component-detection-exclusions.yml

extends:
  template: /.azdo/linux/pipeline_base.yml@self
  parameters:
    image: ubuntu-24.04-PME-GPT
    BxlExtraArgs: /p:BUILDXL_FINGERPRINT_SALT=Ubuntu2404