trigger: none 

resources:
  repositories:
  - repository: 1esPipelines
    type: git
    name: Domino/1ESPipelines
    ref: refs/heads/main

parameters:
- name: pool
  type: object
  default: 
    name: BuildXL-DevOpsAgents-Selfhost-BuildCache
    image: ubuntu-22.04-PME-GPT
    os: linux

extends:
  template: v1/1ES.Official.VhdGeneration.PipelineTemplate.yml@1esPipelines
  parameters:
    pool: ${{ parameters.pool }}
    sdl:
      # Source analyses enabled by default:
      #   https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/overview#behavior-in-pipelines-extending-unofficial-template
      #
      # TODO: Move SDL source analyses to the rolling pipline when they can be enabled even when there are CB builds.
      #       Ideally, we should only enable source analyses in the rolling pipeline. However, because our rolling pipeline contains CB builds, SDL source analyses are all disabled,
      #       in favor of the CB compliance build. Unfortunately, some analyses, like policheck, do not work in network isolation when building in CB.
      #       SDL source analyses typically take 2.5-4 minutes, and should not be in the critical path of this pipeline run.
      psscriptanalyzer:
        enabled: true
      policheck:
        enabled: true
      sourceAnalysisPool:
        name: Windows-SDL-Agents
        image: Windows-SDL-Image
        os: windows
