// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// xunit v3 requires test assemblies to be executables with entry points and
// certain assembly-level registrations. In standard MSBuild projects, these are
// auto-generated by the xunit.v3.core.mtp-v1 and Microsoft.Testing.Platform.MSBuild
// NuGet package targets. Since BuildXL uses DScript instead of MSBuild, we provide
// them here as a single source file that the XUnitV3 framework injects automatically.
//
// This file consolidates:
//   - XunitAutoGeneratedEntryPoint: Main() that dispatches to Microsoft Testing Platform or console runner
//   - SelfRegisteredExtensions: Microsoft Testing Platform extension registration hooks
//   - DefaultRunnerReporters: assembly-level runner reporter registrations
//
// Test projects should NOT need to include this file directly. Instead, use
// XUnitV3.testAsExecutable() in the .dsc file and it will be injected as a source.

// ---- Runner reporter registrations (from xunit.v3.core.mtp-v1/_content/DefaultRunnerReporters.cs) ----
[assembly: global::Xunit.Runner.Common.RegisterRunnerReporter(typeof(global::Xunit.Runner.Common.DefaultRunnerReporter))]
[assembly: global::Xunit.Runner.Common.RegisterRunnerReporter(typeof(global::Xunit.Runner.Common.JsonReporter))]
[assembly: global::Xunit.Runner.Common.RegisterRunnerReporter(typeof(global::Xunit.Runner.Common.QuietReporter))]
[assembly: global::Xunit.Runner.Common.RegisterRunnerReporter(typeof(global::Xunit.Runner.Common.SilentReporter))]
[assembly: global::Xunit.Runner.Common.RegisterRunnerReporter(typeof(global::Xunit.Runner.Common.VerboseReporter))]
[assembly: global::Xunit.Runner.Common.RegisterRunnerReporter(typeof(global::Xunit.Runner.Common.VstsReporter))]

namespace Xunit.V3.BuildXL.Generated
{
    // ---- Entry point (from xunit.v3.core.mtp-v1 XunitGenerateEntryPoint MSBuild task) ----
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal class XunitEntryPoint
    {
        public static int Main(string[] args)
        {
            if (global::System.Linq.Enumerable.Any(args, arg => arg == "--server" || arg == "--internal-msbuild-node"))
                return global::Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(args, SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult();
            else
                return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
        }
    }

    // ---- Microsoft Testing Platform self-registration (from Microsoft.Testing.Platform.MSBuild) ----
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal static class SelfRegisteredExtensions
    {
        public static void AddSelfRegisteredExtensions(this global::Microsoft.Testing.Platform.Builder.ITestApplicationBuilder builder, string[] args)
        {
            global::Microsoft.Testing.Platform.MSBuild.TestingPlatformBuilderHook.AddExtensions(builder, args);
            global::Microsoft.Testing.Extensions.Telemetry.TestingPlatformBuilderHook.AddExtensions(builder, args);
        }
    }
}
